---
job: "extension"
config:
  name: "lora_flux_amol_v3"
  process:
    - type: "diffusion_trainer"
      training_folder: "/home/amold163/ai-toolkit/output"
      sqlite_db_path: "./aitk_db.db"
      device: "cuda"
      trigger_word: "amolface"
      performance_log_every: 10
      network:
        type: "lora"
        linear: 32
        linear_alpha: 32
        conv: 16
        conv_alpha: 16
        lokr_full_rank: true
        lokr_factor: -1
        network_kwargs:
          ignore_if_contains: []
      save:
        dtype: "bf16"
        save_every: 250
        max_step_saves_to_keep: 4
        save_format: "diffusers"
        push_to_hub: false
      datasets:
        - folder_path: "/home/amold163/ai-toolkit/datasets/amolperson"
          mask_path: null
          mask_min_value: 0.1
          default_caption: "amolface"
          caption_ext: "txt"
          caption_dropout_rate: 0.05
          cache_latents_to_disk: false
          is_reg: false
          network_weight: 1
          resolution:
            - 1024
          controls: []
          shrink_video_to_frames: true
          num_frames: 1
          flip_x: false
          flip_y: false
          num_repeats: 1
      train:
        batch_size: 10
        bypass_guidance_embedding: false
        steps: 3000
        gradient_accumulation: 1
        train_unet: true
        train_text_encoder: false
        gradient_checkpointing: true
        noise_scheduler: "flowmatch"
        optimizer: "adamw8bit"
        timestep_type: "sigmoid"
        content_or_style: "balanced"
        optimizer_params:
          weight_decay: 0.0001
        unload_text_encoder: false
        cache_text_embeddings: false
        lr: 0.0001
        ema_config:
          use_ema: false
          ema_decay: 0.99
        skip_first_sample: false
        force_first_sample: false
        disable_sampling: false
        dtype: "bf16"
        diff_output_preservation: false
        diff_output_preservation_multiplier: 1
        diff_output_preservation_class: "person"
        switch_boundary_every: 1
        loss_type: "mse"
      logging:
        log_every: 1
        use_ui_logger: true
      model:
        name_or_path: "black-forest-labs/FLUX.1-dev"
        quantize: false
        quantize_te: false
        arch: "flux"
        low_vram: false
        model_kwargs: {}
      sample:
        sampler: "flowmatch"
        sample_every: 250
        width: 1024
        height: 1024
        samples:
          - prompt: "amolface with red hair, playing chess at the park, bomb going off in the background"
          - prompt: "a amolface  holding a coffee cup, in a beanie, sitting at a cafe"
          - prompt: "a amolface is a DJ at a night club, fish eye lens, smoke machine, lazer lights, holding a martini"
          - prompt: "a amolface  showing off his cool new t shirt at the beach, a shark is jumping out of the water in the background"
          - prompt: "a amolface  building a log cabin in the snow covered mountains"
          - prompt: "amolface  playing the guitar, on stage, singing a song, laser lights, punk rocker"
          - prompt: "hipster amolface with a beard, building a chair, in a wood shop"
          - prompt: "photo of a amolface , white background, medium shot, modeling clothing, studio lighting, white backdrop"
          - prompt: "a amolface holding a sign that says, 'this is a sign'"
          - prompt: "a amolface , in a post apocalyptic world, with a shotgun, in a leather jacket, in a desert, with a motorcycle"
        neg: ""
        seed: 42
        walk_seed: true
        guidance_scale: 4
        sample_steps: 30
        num_frames: 1
        fps: 1
meta:
  name: "[name]"
  version: "1.0"
